export const SUBJECTS = [
  "MATEMATIKA",
  "ILMU PENGETAHUAN ALAM (IPA)",
  "ILMU PENGETAHUAN SOSIAL (IPS)",
  "BAHASA INDONESIA",
  "BAHASA INGGRIS",
  "SENI BUDAYA",
  "TEKNOLOGI INFORMASI DAN KOMPUTER",
  "OLAHRAGA",
];
